name: Test & Benchmark

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_and_benchmark:
    name: Run all tests & benchmarks
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
    - name: Check out code
      uses: actions/checkout@v3
    - name: Run test
      run: go test ./... -benchmem -bench .
