name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Run test
      run: go test ./... -benchmem -bench .
